name: 🚀 Deploy RoomyFrontend

on:
  push:
    branches:
      - main  # Cambia al branch que uses para producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout repo
        uses: actions/checkout@v3

      - name: 🚀 Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /apps/roomy-app/roomy-frontend
            git reset --hard
            git clean -fd
            git pull origin main
            npm install
            npm run build
            pm2 restart roomy-frontend || pm2 start npm --name roomy-frontend -- start

